# Generated by Django 3.1.4 on 2021-01-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.FileField(null=True, upload_to='')),
                ('discription', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='client_tail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('paragraph', models.CharField(max_length=90)),
                ('image', models.FileField(null=True, upload_to='')),
                ('facebook', models.URLField(max_length=90, null=True)),
                ('instagram', models.URLField(max_length=90, null=True)),
                ('website', models.URLField(max_length=90, null=True)),
                ('twitter', models.URLField(max_length=90, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profression', models.CharField(max_length=50)),
                ('discription', models.CharField(max_length=100)),
                ('image', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SERVICES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
                ('service_paragraph', models.CharField(max_length=1000)),
                ('service_logo', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='story_of_vistaar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('employee_Position', models.CharField(max_length=50)),
                ('employee_discription', models.CharField(max_length=100)),
                ('employee_twitter', models.URLField(max_length=50, null=True)),
                ('employee_facebook', models.URLField(max_length=50, null=True)),
                ('employee_linkedin', models.URLField(max_length=50, null=True)),
                ('employee_insta', models.URLField(max_length=50, null=True)),
                ('employee_image', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
