# Generated by Django 3.1.5 on 2021-01-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzzvis', '0003_auto_20210128_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='discription',
            field=models.TextField(max_length=1500),
        ),
    ]
