# Generated by Django 3.1.5 on 2021-01-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzzvis', '0004_auto_20210128_0754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
